module.exports = {
  TL: {
    country_name: "East Timor",
    currency: "USD",
    code: "USD",
    symbol: "$",
    symbol_native: "$" },
  SS: {
    country_name: "South Sudan",
    currency: "South Sudanese pound",
    code: "SSP",
    symbol: "SS£",
    symbol_native: "SS£" },
  SX: {
    country_name: "Sint Maarten",
    currency: "Netherlands Antilles Guilder",
    code: "ANG",
    symbol: "ANG",
    symbol_native: "ƒ" },
  BQ: {
    country_name: "Bonaire",
    currency: "USD",
    code: "USD",
    symbol: "$",
    symbol_native: "$" },
  NZ: {
    country_name: "New Zealand",
    currency: "New Zealand Dollars",
    code: "NZD",
    symbol: "NZ$",
    symbol_native: "$" },
  CK: {
    country_name: "Cook Islands",
    currency: "New Zealand Dollars",
    code: "NZD",
    symbol: "NZ$",
    symbol_native: "$" },
  NU: {
    country_name: "Niue",
    currency: "New Zealand Dollars",
    code: "NZD",
    symbol: "NZ$",
    symbol_native: "$" },
  PN: {
    country_name: "Pitcairn",
    currency: "New Zealand Dollars",
    code: "NZD",
    symbol: "NZ$",
    symbol_native: "$" },
  TK: {
    country_name: "Tokelau",
    currency: "New Zealand Dollars",
    code: "NZD",
    symbol: "NZ$",
    symbol_native: "$" },
  AU: {
    country_name: "Australian",
    currency: "Australian Dollars",
    code: "AUD",
    symbol: "AU$",
    symbol_native: "$" },
  CX: {
    country_name: "Christmas Island",
    currency: "Australian Dollars",
    code: "AUD",
    symbol: "AU$",
    symbol_native: "$" },
  CC: {
    country_name: "Cocos (Keeling) Islands",
    currency: "Australian Dollars",
    code: "AUD",
    symbol: "AU$",
    symbol_native: "$" },
  HM: {
    country_name: "Heard and Mc Donald Islands",
    currency: "Australian Dollars",
    code: "AUD",
    symbol: "AU$",
    symbol_native: "$" },
  KI: {
    country_name: "Kiribati",
    currency: "Australian Dollars",
    code: "AUD",
    symbol: "AU$",
    symbol_native: "$" },
  NR: {
    country_name: "Nauru",
    currency: "Australian Dollars",
    code: "AUD",
    symbol: "AU$",
    symbol_native: "$" },
  NF: {
    country_name: "Norfolk Island",
    currency: "Australian Dollars",
    code: "AUD",
    symbol: "AU$",
    symbol_native: "$" },
  TV: {
    country_name: "Tuvalu",
    currency: "Australian Dollars",
    code: "AUD",
    symbol: "AU$",
    symbol_native: "$" },
  AS: {
    country_name: "American Samoa",
    currency: "Euros",
    code: "EUR",
    symbol: "€",
    symbol_native: "€" },
  AD: {
    country_name: "Andorra",
    currency: "Euros",
    code: "EUR",
    symbol: "€",
    symbol_native: "€" },
  AT: {
    country_name: "Austria",
    currency: "Euros",
    code: "EUR",
    symbol: "€",
    symbol_native: "€" },
  BE: {
    country_name: "Belgium",
    currency: "Euros",
    code: "EUR",
    symbol: "€",
    symbol_native: "€" },
  FI: {
    country_name: "Finland",
    currency: "Euros",
    code: "EUR",
    symbol: "€",
    symbol_native: "€" },
  FR: {
    country_name: "France",
    currency: "Euros",
    code: "EUR",
    symbol: "€",
    symbol_native: "€" },
  GF: {
    country_name: "French Guiana",
    currency: "Euros",
    code: "EUR",
    symbol: "€",
    symbol_native: "€" },
  TF: {
    country_name: "French Southern Territories",
    currency: "Euros",
    code: "EUR",
    symbol: "€",
    symbol_native: "€" },
  DE: {
    country_name: "Germany",
    currency: "Euros",
    code: "EUR",
    symbol: "€",
    symbol_native: "€" },
  GR: {
    country_name: "Greece",
    currency: "Euros",
    code: "EUR",
    symbol: "€",
    symbol_native: "€" },
  GP: {
    country_name: "Guadeloupe",
    currency: "Euros",
    code: "EUR",
    symbol: "€",
    symbol_native: "€" },
  IE: {
    country_name: "Ireland",
    currency: "Euros",
    code: "EUR",
    symbol: "€",
    symbol_native: "€" },
  IT: {
    country_name: "Italy",
    currency: "Euros",
    code: "EUR",
    symbol: "€",
    symbol_native: "€" },
  LU: {
    country_name: "Luxembourg",
    currency: "Euros",
    code: "EUR",
    symbol: "€",
    symbol_native: "€" },
  MQ: {
    country_name: "Martinique",
    currency: "Euros",
    code: "EUR",
    symbol: "€",
    symbol_native: "€" },
  YT: {
    country_name: "Mayotte",
    currency: "Euros",
    code: "EUR",
    symbol: "€",
    symbol_native: "€" },
  MC: {
    country_name: "Monaco",
    currency: "Euros",
    code: "EUR",
    symbol: "€",
    symbol_native: "€" },
  NL: {
    country_name: "Netherlands",
    currency: "Euros",
    code: "EUR",
    symbol: "€",
    symbol_native: "€" },
  PT: {
    country_name: "Portugal",
    currency: "Euros",
    code: "EUR",
    symbol: "€",
    symbol_native: "€" },
  RE: {
    country_name: "Reunion",
    currency: "Euros",
    code: "EUR",
    symbol: "€",
    symbol_native: "€" },
  WS: {
    country_name: "Samoa",
    currency: "Euros",
    code: "EUR",
    symbol: "€",
    symbol_native: "€" },
  SM: {
    country_name: "San Marino",
    currency: "Euros",
    code: "EUR",
    symbol: "€",
    symbol_native: "€" },
  SI: {
    country_name: "Slovenia",
    currency: "Euros",
    code: "EUR",
    symbol: "€",
    symbol_native: "€" },
  ES: {
    country_name: "Spain",
    currency: "Euros",
    code: "EUR",
    symbol: "€",
    symbol_native: "€" },
  VA: {
    country_name: "Vatican City State (Holy See)",
    currency: "Euros",
    code: "EUR",
    symbol: "€",
    symbol_native: "€" },
  GS: {
    country_name: "South Georgia and the South Sandwich Islands",
    currency: "Sterling",
    code: "GBP",
    symbol: "£",
    symbol_native: "£" },
  GB: {
    country_name: "United Kingdom",
    currency: "Sterling",
    code: "GBP",
    symbol: "£",
    symbol_native: "£" },
  JE: {
    country_name: "Jersey",
    currency: "Sterling",
    code: "GBP",
    symbol: "£",
    symbol_native: "£" },
  IO: {
    country_name: "British Indian Ocean Territory",
    currency: "USD",
    code: "USD",
    symbol: "$",
    symbol_native: "$" },
  GU: {
    country_name: "Guam",
    currency: "USD",
    code: "USD",
    symbol: "$",
    symbol_native: "$" },
  MH: {
    country_name: "Marshall Islands",
    currency: "USD",
    code: "USD",
    symbol: "$",
    symbol_native: "$" },
  FM: {
    country_name: "Micronesia Federated States of",
    currency: "USD",
    code: "USD",
    symbol: "$",
    symbol_native: "$" },
  MP: {
    country_name: "Northern Mariana Islands",
    currency: "USD",
    code: "USD",
    symbol: "$",
    symbol_native: "$" },
  PW: {
    country_name: "Palau",
    currency: "USD",
    code: "USD",
    symbol: "$",
    symbol_native: "$" },
  PR: {
    country_name: "Puerto Rico",
    currency: "USD",
    code: "USD",
    symbol: "$",
    symbol_native: "$" },
  TC: {
    country_name: "Turks and Caicos Islands",
    currency: "USD",
    code: "USD",
    symbol: "$",
    symbol_native: "$" },
  US: {
    country_name: "United States",
    currency: "USD",
    code: "USD",
    symbol: "$",
    symbol_native: "$" },
  UM: {
    country_name: "United States Minor Outlying Islands",
    currency: "USD",
    code: "USD",
    symbol: "$",
    symbol_native: "$" },
  VG: {
    country_name: "Virgin Islands (British)",
    currency: "USD",
    code: "USD",
    symbol: "$",
    symbol_native: "$" },
  VI: {
    country_name: "Virgin Islands (US)",
    currency: "USD",
    code: "USD",
    symbol: "$",
    symbol_native: "$" },
  HK: {
    country_name: "Hong Kong",
    currency: "HKD",
    code: "HKD",
    symbol: "HK$",
    symbol_native: "$" },
  CA: {
    country_name: "Canada",
    currency: "Canadian Dollar",
    code: "CAD",
    symbol: "CA$",
    symbol_native: "$" },
  JP: {
    country_name: "Japan",
    currency: "Japanese Yen",
    code: "JPY",
    symbol: "¥",
    symbol_native: "￥" },
  AF: {
    country_name: "Afghanistan",
    currency: "Afghani",
    code: "AFN",
    symbol: "Af",
    symbol_native: "؋" },
  AL: {
    country_name: "Albania",
    currency: "Lek",
    code: "ALL",
    symbol: "ALL",
    symbol_native: "Lek" },
  DZ: {
    country_name: "Algeria",
    currency: "Algerian Dinar",
    code: "DZD",
    symbol: "DA",
    symbol_native: "د.ج.‏" },
  AI: {
    country_name: "Anguilla",
    currency: "East Caribbean Dollar",
    code: "XCD",
    symbol: "XCD",
    symbol_native: "$" },
  AG: {
    country_name: "Antigua and Barbuda",
    currency: "East Caribbean Dollar",
    code: "XCD",
    symbol: "XCD",
    symbol_native: "$" },
  DM: {
    country_name: "Dominica",
    currency: "East Caribbean Dollar",
    code: "XCD",
    symbol: "XCD",
    symbol_native: "$" },
  GD: {
    country_name: "Grenada",
    currency: "East Caribbean Dollar",
    code: "XCD",
    symbol: "XCD",
    symbol_native: "$" },
  MS: {
    country_name: "Montserrat",
    currency: "East Caribbean Dollar",
    code: "XCD",
    symbol: "XCD",
    symbol_native: "$" },
  KN: {
    country_name: "Saint Kitts",
    currency: "East Caribbean Dollar",
    code: "XCD",
    symbol: "XCD",
    symbol_native: "$" },
  LC: {
    country_name: "Saint Lucia",
    currency: "East Caribbean Dollar",
    code: "XCD",
    symbol: "XCD",
    symbol_native: "$" },
  VC: {
    country_name: "Saint Vincent Grenadines",
    currency: "East Caribbean Dollar",
    code: "XCD",
    symbol: "XCD",
    symbol_native: "$" },
  AR: {
    country_name: "Argentina",
    currency: "Peso",
    code: "ARS",
    symbol: "AR$",
    symbol_native: "$" },
  AM: {
    country_name: "Armenia",
    currency: "Dram",
    code: "AMD",
    symbol: "AMD",
    symbol_native: "դր." },
  AW: {
    country_name: "Aruba",
    currency: "Netherlands Antilles Guilder",
    code: "ANG",
    symbol: "ANG",
    symbol_native: "ƒ" },
  AN: {
    country_name: "Netherlands Antilles",
    currency: "Netherlands Antilles Guilder",
    code: "ANG",
    symbol: "ANG",
    symbol_native: "ƒ" },
  AZ: {
    country_name: "Azerbaijan",
    currency: "Manat",
    code: "AZN",
    symbol: "man.",
    symbol_native: "ман." },
  BS: {
    country_name: "Bahamas",
    currency: "Bahamian Dollar",
    code: "BSD",
    symbol: "BSD",
    symbol_native: "$" },
  BH: {
    country_name: "Bahrain",
    currency: "Bahraini Dinar",
    code: "BHD",
    symbol: "BD",
    symbol_native: "د.ب.‏" },
  BD: {
    country_name: "Bangladesh",
    currency: "Taka",
    code: "BDT",
    symbol: "Tk",
    symbol_native: "৳" },
  BB: {
    country_name: "Barbados",
    currency: "Barbadian Dollar",
    code: "BBD",
    symbol: "BDD",
    symbol_native: "$" },
  BY: {
    country_name: "Belarus",
    currency: "Belarus Ruble",
    code: "BYR",
    symbol: "BYR",
    symbol_native: "BYR" },
  BZ: {
    country_name: "Belize",
    currency: "Belizean Dollar",
    code: "BZD",
    symbol: "BZ$",
    symbol_native: "$" },
  BJ: {
    country_name: "Benin",
    currency: "CFA Franc BCEAO",
    code: "XOF",
    symbol: "CFA",
    symbol_native: "CFA" },
  BF: {
    country_name: "Burkina Faso",
    currency: "CFA Franc BCEAO",
    code: "XOF",
    symbol: "CFA",
    symbol_native: "CFA" },
  GW: {
    country_name: "Guinea-Bissau",
    currency: "CFA Franc BCEAO",
    code: "XOF",
    symbol: "CFA",
    symbol_native: "CFA" },
  CI: {
    country_name: "Ivory Coast",
    currency: "CFA Franc BCEAO",
    code: "XOF",
    symbol: "CFA",
    symbol_native: "CFA" },
  ML: {
    country_name: "Mali",
    currency: "CFA Franc BCEAO",
    code: "XOF",
    symbol: "CFA",
    symbol_native: "CFA" },
  NE: {
    country_name: "Niger",
    currency: "CFA Franc BCEAO",
    code: "XOF",
    symbol: "CFA",
    symbol_native: "CFA" },
  SN: {
    country_name: "Senegal",
    currency: "CFA Franc BCEAO",
    code: "XOF",
    symbol: "CFA",
    symbol_native: "CFA" },
  TG: {
    country_name: "Togo",
    currency: "CFA Franc BCEAO",
    code: "XOF",
    symbol: "CFA",
    symbol_native: "CFA" },
  BM: {
    country_name: "Bermuda",
    currency: "Bermudian Dollar",
    code: "BMD",
    symbol: "BMD",
    symbol_native: "$" },
  BT: {
    country_name: "Bhutan",
    currency: "Indian Rupee",
    code: "INR",
    symbol: "Rs",
    symbol_native: "টকা" },
  IN: {
    country_name: "India",
    currency: "Indian Rupee",
    code: "INR",
    symbol: "Rs",
    symbol_native: "টকা" },
  BO: {
    country_name: "Bolivia",
    currency: "Boliviano",
    code: "BOB",
    symbol: "Bs",
    symbol_native: "Bs" },
  BW: {
    country_name: "Botswana",
    currency: "Pula",
    code: "BWP",
    symbol: "BWP",
    symbol_native: "P" },
  BV: {
    country_name: "Bouvet Island",
    currency: "Norwegian Krone",
    code: "NOK",
    symbol: "Nkr",
    symbol_native: "kr" },
  NO: {
    country_name: "Norway",
    currency: "Norwegian Krone",
    code: "NOK",
    symbol: "Nkr",
    symbol_native: "kr" },
  SJ: {
    country_name: "Svalbard and Jan Mayen Islands",
    currency: "Norwegian Krone",
    code: "NOK",
    symbol: "Nkr",
    symbol_native: "kr" },
  BR: {
    country_name: "Brazil",
    currency: "Brazil",
    code: "BRL",
    symbol: "R$",
    symbol_native: "R$" },
  BN: {
    country_name: "Brunei Darussalam",
    currency: "Bruneian Dollar",
    code: "BND",
    symbol: "BN$",
    symbol_native: "$" },
  BG: {
    country_name: "Bulgaria",
    currency: "Lev",
    code: "BGN",
    symbol: "BGN",
    symbol_native: "лв." },
  BI: {
    country_name: "Burundi",
    currency: "Burundi Franc",
    code: "BIF",
    symbol: "FBu",
    symbol_native: "FBu" },
  KH: {
    country_name: "Cambodia",
    currency: "Riel",
    code: "KHR",
    symbol: "KHR",
    symbol_native: "៛" },
  CM: {
    country_name: "Cameroon",
    currency: "CFA Franc BEAC",
    code: "XAF",
    symbol: "FCFA",
    symbol_native: "FCFA" },
  CF: {
    country_name: "Central African Republic",
    currency: "CFA Franc BEAC",
    code: "XAF",
    symbol: "FCFA",
    symbol_native: "FCFA" },
  TD: {
    country_name: "Chad",
    currency: "CFA Franc BEAC",
    code: "XAF",
    symbol: "FCFA",
    symbol_native: "FCFA" },
  CG: {
    country_name: "Congo Republic of the Democratic",
    currency: "CFA Franc BEAC",
    code: "XAF",
    symbol: "FCFA",
    symbol_native: "FCFA" },
  GQ: {
    country_name: "Equatorial Guinea",
    currency: "CFA Franc BEAC",
    code: "XAF",
    symbol: "FCFA",
    symbol_native: "FCFA" },
  GA: {
    country_name: "Gabon",
    currency: "CFA Franc BEAC",
    code: "XAF",
    symbol: "FCFA",
    symbol_native: "FCFA" },
  CV: {
    country_name: "Cape Verde",
    currency: "Escudo",
    code: "CVE",
    symbol: "CV$",
    symbol_native: "CV$" },
  KY: {
    country_name: "Cayman Islands",
    currency: "Caymanian Dollar",
    code: "KYD",
    symbol: "KYD",
    symbol_native: "$" },
  CL: {
    country_name: "Chile",
    currency: "Chilean Peso",
    code: "CLP",
    symbol: "CL$",
    symbol_native: "$" },
  CN: {
    country_name: "China",
    currency: "Yuan Renminbi",
    code: "CNY",
    symbol: "CN¥",
    symbol_native: "CN¥" },
  CO: {
    country_name: "Colombia",
    currency: "Peso",
    code: "COP",
    symbol: "CO$",
    symbol_native: "$" },
  KM: {
    country_name: "Comoros",
    currency: "Comoran Franc",
    code: "KMF",
    symbol: "CF",
    symbol_native: "FC" },
  CD: {
    country_name: "Congo (Kinshasa)",
    currency: "Congolese Frank",
    code: "CDF",
    symbol: "CDF",
    symbol_native: "FrCD" },
  CR: {
    country_name: "Costa Rica",
    currency: "Costa Rican Colon",
    code: "CRC",
    symbol: "₡",
    symbol_native: "₡" },
  HR: {
    country_name: "Croatia (Hrvatska)",
    currency: "Croatian Dinar",
    code: "HRK",
    symbol: "kn",
    symbol_native: "kn" },
  CU: {
    country_name: "Cuba",
    currency: "Cuban Peso",
    code: "CUP",
    symbol: "CUP",
    symbol_native: "₱" },
  CY: {
    country_name: "Cyprus",
    currency: "Cypriot Pound",
    code: "CYP",
    symbol: "£",
    symbol_native: "£" },
  CZ: {
    country_name: "Czech Republic",
    currency: "Koruna",
    code: "CZK",
    symbol: "Kč",
    symbol_native: "Kč" },
  DK: {
    country_name: "Denmark",
    currency: "Danish Krone",
    code: "DKK",
    symbol: "Dkr",
    symbol_native: "kr" },
  FO: {
    country_name: "Faroe Islands",
    currency: "Danish Krone",
    code: "DKK",
    symbol: "Dkr",
    symbol_native: "kr" },
  GL: {
    country_name: "Greenland",
    currency: "Danish Krone",
    code: "DKK",
    symbol: "Dkr",
    symbol_native: "kr" },
  DJ: {
    country_name: "Djibouti",
    currency: "Djiboutian Franc",
    code: "DJF",
    symbol: "Fdj",
    symbol_native: "Fdj" },
  DO: {
    country_name: "Dominican Republic",
    currency: "Dominican Peso",
    code: "DOP",
    symbol: "RD$",
    symbol_native: "RD$" },
  TP: {
    country_name: "East Timor",
    currency: "Indonesian Rupiah",
    code: "IDR",
    symbol: "Rp",
    symbol_native: "Rp" },
  ID: {
    country_name: "Indonesia",
    currency: "Indonesian Rupiah",
    code: "IDR",
    symbol: "Rp",
    symbol_native: "Rp" },
  EC: {
    country_name: "Ecuador",
    currency: "Sucre",
    code: "ECS",
    symbol: "ECS",
    symbol_native: "S/." },
  EG: {
    country_name: "Egypt",
    currency: "Egyptian Pound",
    code: "EGP",
    symbol: "EGP",
    symbol_native: "ج.م.‏" },
  SV: {
    country_name: "El Salvador",
    currency: "Salvadoran Colon",
    code: "SVC",
    symbol: "SVC",
    symbol_native: "$" },
  ER: {
    country_name: "Eritrea",
    currency: "Ethiopian Birr",
    code: "ETB",
    symbol: "Br",
    symbol_native: "Br" },
  ET: {
    country_name: "Ethiopia",
    currency: "Ethiopian Birr",
    code: "ETB",
    symbol: "Br",
    symbol_native: "Br" },
  EE: {
    country_name: "Estonia",
    currency: "Estonian Kroon",
    code: "EEK",
    symbol: "Ekr",
    symbol_native: "kr" },
  FK: {
    country_name: "Falkland Islands (Malvinas)",
    currency: "Falkland Pound",
    code: "FKP",
    symbol: "FKP",
    symbol_native: "FKP" },
  FJ: {
    country_name: "Fiji",
    currency: "Fijian Dollar",
    code: "FJD",
    symbol: "FJD",
    symbol_native: "FJD" },
  PF: {
    country_name: "French Polynesia",
    currency: "CFP Franc",
    code: "XPF",
    symbol: "XPF",
    symbol_native: "XPF" },
  NC: {
    country_name: "New Caledonia",
    currency: "CFP Franc",
    code: "XPF",
    symbol: "XPF",
    symbol_native: "XPF" },
  WF: {
    country_name: "Wallis and Futuna Islands",
    currency: "CFP Franc",
    code: "XPF",
    symbol: "XPF",
    symbol_native: "XPF" },
  GM: {
    country_name: "Gambia",
    currency: "Dalasi",
    code: "GMD",
    symbol: "GMD",
    symbol_native: "GMD" },
  GE: {
    country_name: "Georgia",
    currency: "Lari",
    code: "GEL",
    symbol: "GEL",
    symbol_native: "GEL" },
  GI: {
    country_name: "Gibraltar",
    currency: "Gibraltar Pound",
    code: "GIP",
    symbol: "GIP",
    symbol_native: "GIP" },
  GT: {
    country_name: "Guatemala",
    currency: "Quetzal",
    code: "GTQ",
    symbol: "GTQ",
    symbol_native: "Q" },
  GN: {
    country_name: "Guinea",
    currency: "Guinean Franc",
    code: "GNF",
    symbol: "FG",
    symbol_native: "FG" },
  GY: {
    country_name: "Guyana",
    currency: "Guyanaese Dollar",
    code: "GYD",
    symbol: "GYD",
    symbol_native: "GYD" },
  HT: {
    country_name: "Haiti",
    currency: "Gourde",
    code: "HTG",
    symbol: "HTG",
    symbol_native: "HTG" },
  HN: {
    country_name: "Honduras",
    currency: "Lempira",
    code: "HNL",
    symbol: "HNL",
    symbol_native: "L" },
  HU: {
    country_name: "Hungary",
    currency: "Forint",
    code: "HUF",
    symbol: "Ft",
    symbol_native: "Ft" },
  IS: {
    country_name: "Iceland",
    currency: "Icelandic Krona",
    code: "ISK",
    symbol: "Ikr",
    symbol_native: "kr" },
  IR: {
    country_name: "Iran (Islamic Republic of)",
    currency: "Iranian Rial",
    code: "IRR",
    symbol: "IRR",
    symbol_native: "﷼" },
  IQ: {
    country_name: "Iraq",
    currency: "Iraqi Dinar",
    code: "IQD",
    symbol: "IQD",
    symbol_native: "د.ع.‏" },
  IL: {
    country_name: "Israel",
    currency: "Shekel",
    code: "ILS",
    symbol: "₪",
    symbol_native: "₪" },
  JM: {
    country_name: "Jamaica",
    currency: "Jamaican Dollar",
    code: "JMD",
    symbol: "J$",
    symbol_native: "$" },
  JO: {
    country_name: "Jordan",
    currency: "Jordanian Dinar",
    code: "JOD",
    symbol: "JD",
    symbol_native: "د.أ.‏" },
  KZ: {
    country_name: "Kazakhstan",
    currency: "Tenge",
    code: "KZT",
    symbol: "KZT",
    symbol_native: "тңг." },
  KE: {
    country_name: "Kenya",
    currency: "Kenyan Shilling",
    code: "KES",
    symbol: "Ksh",
    symbol_native: "Ksh" },
  KP: {
    country_name: "Korea North",
    currency: "Won",
    code: "KPW",
    symbol: "KPW",
    symbol_native: "KPW" },
  KR: {
    country_name: "Korea South",
    currency: "Won",
    code: "KRW",
    symbol: "₩",
    symbol_native: "₩" },
  KW: {
    country_name: "Kuwait",
    currency: "Kuwaiti Dinar",
    code: "KWD",
    symbol: "KD",
    symbol_native: "د.ك.‏" },
  KG: {
    country_name: "Kyrgyzstan",
    currency: "Som",
    code: "KGS",
    symbol: "KGS",
    symbol_native: "KGS" },
  LA: {
    country_name: "Laos",
    currency: "Lao kip",
    code: "LAK",
    symbol: "LAK",
    symbol_native: "LAK" },
  LV: {
    country_name: "Latvia",
    currency: "Lat",
    code: "LVL",
    symbol: "Ls",
    symbol_native: "Ls" },
  LB: {
    country_name: "Lebanon",
    currency: "Lebanese Pound",
    code: "LBP",
    symbol: "LB£",
    symbol_native: "ل.ل.‏" },
  LS: {
    country_name: "Lesotho",
    currency: "Loti",
    code: "LSL",
    symbol: "LSL",
    symbol_native: "LSL" },
  LR: {
    country_name: "Liberia",
    currency: "Liberian Dollar",
    code: "LRD",
    symbol: "LRD",
    symbol_native: "LRD" },
  LY: {
    country_name: "Libyan Arab Jamahiriya",
    currency: "Libyan Dinar",
    code: "LYD",
    symbol: "LD",
    symbol_native: "د.ل.‏" },
  LI: {
    country_name: "Liechtenstein",
    currency: "Swiss Franc",
    code: "CHF",
    symbol: "CHF",
    symbol_native: "CHF" },
  CH: {
    country_name: "Switzerland",
    currency: "Swiss Franc",
    code: "CHF",
    symbol: "CHF",
    symbol_native: "CHF" },
  LT: {
    country_name: "Lithuania",
    currency: "Lita",
    code: "LTL",
    symbol: "Lt",
    symbol_native: "Lt" },
  MO: {
    country_name: "Macao S.A.R.",
    currency: "Macanese pataca",
    code: "MOP",
    symbol: "MOP$",
    symbol_native: "MOP$" },
  MK: {
    country_name: "Macedonia",
    currency: "Denar",
    code: "MKD",
    symbol: "MKD",
    symbol_native: "MKD" },
  MG: {
    country_name: "Madagascar",
    currency: "Malagasy Franc",
    code: "MGA",
    symbol: "MGA",
    symbol_native: "MGA" },
  MW: {
    country_name: "Malawi",
    currency: "Malawian Kwacha",
    code: "MWK",
    symbol: "MWK",
    symbol_native: "MWK" },
  MY: {
    country_name: "Malaysia",
    currency: "Ringgit",
    code: "MYR",
    symbol: "RM",
    symbol_native: "RM" },
  MV: {
    country_name: "Maldives",
    currency: "Rufiyaa",
    code: "MVR",
    symbol: "MVR",
    symbol_native: "MVR" },
  MT: {
    country_name: "Malta",
    currency: "Maltese Lira",
    code: "MTL",
    symbol: "MTL",
    symbol_native: "MTL" },
  MR: {
    country_name: "Mauritania",
    currency: "Ouguiya",
    code: "MRO",
    symbol: "MRO",
    symbol_native: "MRO" },
  MU: {
    country_name: "Mauritius",
    currency: "Mauritian Rupee",
    code: "MUR",
    symbol: "MURs",
    symbol_native: "MURs" },
  MX: {
    country_name: "Mexico",
    currency: "Peso",
    code: "MXN",
    symbol: "MX$",
    symbol_native: "$" },
  MD: {
    country_name: "Moldova Republic of",
    currency: "Leu",
    code: "MDL",
    symbol: "MDL",
    symbol_native: "MDL" },
  MN: {
    country_name: "Mongolia",
    currency: "Tugrik",
    code: "MNT",
    symbol: "MNT",
    symbol_native: "MNT" },
  MA: {
    country_name: "Morocco",
    currency: "Dirham",
    code: "MAD",
    symbol: "MAD",
    symbol_native: "د.م.‏" },
  EH: {
    country_name: "Western Sahara",
    currency: "Dirham",
    code: "MAD",
    symbol: "MAD",
    symbol_native: "د.م.‏" },
  MZ: {
    country_name: "Mozambique",
    currency: "Metical",
    code: "MZN",
    symbol: "MTn",
    symbol_native: "MTn" },
  MM: {
    country_name: "Myanmar",
    currency: "Kyat",
    code: "MMK",
    symbol: "MMK",
    symbol_native: "K" },
  NA: {
    country_name: "Namibia",
    currency: "Dollar",
    code: "NAD",
    symbol: "N$",
    symbol_native: "N$" },
  NP: {
    country_name: "Nepal",
    currency: "Nepalese Rupee",
    code: "NPR",
    symbol: "NPRs",
    symbol_native: "नेरू" },
  NI: {
    country_name: "Nicaragua",
    currency: "Cordoba Oro",
    code: "NIO",
    symbol: "C$",
    symbol_native: "C$" },
  NG: {
    country_name: "Nigeria",
    currency: "Naira",
    code: "NGN",
    symbol: "₦",
    symbol_native: "₦" },
  OM: {
    country_name: "Oman",
    currency: "Sul Rial",
    code: "OMR",
    symbol: "OMR",
    symbol_native: "ر.ع.‏" },
  PK: {
    country_name: "Pakistan",
    currency: "Rupee",
    code: "PKR",
    symbol: "PKRs",
    symbol_native: "₨" },
  PA: {
    country_name: "Panama",
    currency: "Balboa",
    code: "PAB",
    symbol: "B/.",
    symbol_native: "B/." },
  PG: {
    country_name: "Papua New Guinea",
    currency: "Kina",
    code: "PGK",
    symbol: "PGK",
    symbol_native: "PGK" },
  PY: {
    country_name: "Paraguay",
    currency: "Guarani",
    code: "PYG",
    symbol: "₲",
    symbol_native: "₲" },
  PE: {
    country_name: "Peru",
    currency: "Nuevo Sol",
    code: "PEN",
    symbol: "S/.",
    symbol_native: "S/." },
  PH: {
    country_name: "Philippines",
    currency: "Peso",
    code: "PHP",
    symbol: "₱",
    symbol_native: "₱" },
  PL: {
    country_name: "Poland",
    currency: "Zloty",
    code: "PLN",
    symbol: "zł",
    symbol_native: "zł" },
  QA: {
    country_name: "Qatar",
    currency: "Rial",
    code: "QAR",
    symbol: "QR",
    symbol_native: "ر.ق.‏" },
  RO: {
    country_name: "Romania",
    currency: "Leu",
    code: "RON",
    symbol: "RON",
    symbol_native: "RON" },
  RU: {
    country_name: "Russian Federation",
    currency: "Ruble",
    code: "RUB",
    symbol: "RUB",
    symbol_native: "руб." },
  RW: {
    country_name: "Rwanda",
    currency: "Rwanda Franc",
    code: "RWF",
    symbol: "RWF",
    symbol_native: "FR" },
  ST: {
    country_name: "Sao Tome and Principe",
    currency: "Dobra",
    code: "STD",
    symbol: "STD",
    symbol_native: "STD" },
  SA: {
    country_name: "Saudi Arabia",
    currency: "Riyal",
    code: "SAR",
    symbol: "SR",
    symbol_native: "ر.س.‏" },
  SC: {
    country_name: "Seychelles",
    currency: "Rupee",
    code: "SCR",
    symbol: "SCR",
    symbol_native: "SCR" },
  SL: {
    country_name: "Sierra Leone",
    currency: "Leone",
    code: "SLL",
    symbol: "SLL",
    symbol_native: "SLL" },
  SG: {
    country_name: "Singapore",
    currency: "Dollar",
    code: "SGD",
    symbol: "S$",
    symbol_native: "$" },
  SK: {
    country_name: "Slovakia (Slovak Republic)",
    currency: "Koruna",
    code: "SKK",
    symbol: "SKK",
    symbol_native: "SKK" },
  SB: {
    country_name: "Solomon Islands",
    currency: "Solomon Islands Dollar",
    code: "SBD",
    symbol: "SBD",
    symbol_native: "SBD" },
  SO: {
    country_name: "Somalia",
    currency: "Shilling",
    code: "SOS",
    symbol: "Ssh",
    symbol_native: "Ssh" },
  ZA: {
    country_name: "South Africa",
    currency: "Rand",
    code: "ZAR",
    symbol: "R",
    symbol_native: "R" },
  LK: {
    country_name: "Sri Lanka",
    currency: "Rupee",
    code: "LKR",
    symbol: "SLRs",
    symbol_native: "SL Re" },
  SD: {
    country_name: "Sudan",
    currency: "Dinar",
    code: "SDG",
    symbol: "SDG",
    symbol_native: "SDG" },
  SR: {
    country_name: "Suriname",
    currency: "Surinamese Guilder",
    code: "SRD",
    symbol: "SRD",
    symbol_native: "SRD" },
  SZ: {
    country_name: "Swaziland",
    currency: "Lilangeni",
    code: "SZL",
    symbol: "SZL",
    symbol_native: "SZL" },
  SE: {
    country_name: "Sweden",
    currency: "Krona",
    code: "SEK",
    symbol: "Skr",
    symbol_native: "kr" },
  SY: {
    country_name: "Syrian Arab Republic",
    currency: "Syrian Pound",
    code: "SYP",
    symbol: "SY£",
    symbol_native: "ل.س.‏" },
  TW: {
    country_name: "Taiwan",
    currency: "Dollar",
    code: "TWD",
    symbol: "NT$",
    symbol_native: "NT$" },
  TJ: {
    country_name: "Tajikistan",
    currency: "Tajikistan Ruble",
    code: "TJS",
    symbol: "TJS",
    symbol_native: "TJS" },
  TZ: {
    country_name: "Tanzania",
    currency: "Shilling",
    code: "TZS",
    symbol: "TSh",
    symbol_native: "TSh" },
  TH: {
    country_name: "Thailand",
    currency: "Baht",
    code: "THB",
    symbol: "฿",
    symbol_native: "฿" },
  TO: {
    country_name: "Tonga",
    currency: "PaÕanga",
    code: "TOP",
    symbol: "T$",
    symbol_native: "T$" },
  TT: {
    country_name: "Trinidad and Tobago",
    currency: "Trinidad and Tobago Dollar",
    code: "TTD",
    symbol: "TT$",
    symbol_native: "$" },
  TN: {
    country_name: "Tunisia",
    currency: "Tunisian Dinar",
    code: "TND",
    symbol: "DT",
    symbol_native: "د.ت.‏" },
  TR: {
    country_name: "Turkey",
    currency: "Lira",
    code: "TRY",
    symbol: "TL",
    symbol_native: "TL" },
  TM: {
    country_name: "Turkmenistan",
    currency: "Manat",
    code: "TMT",
    symbol: "TMT",
    symbol_native: "TMT" },
  UG: {
    country_name: "Uganda",
    currency: "Shilling",
    code: "UGX",
    symbol: "USh",
    symbol_native: "USh" },
  UA: {
    country_name: "Ukraine",
    currency: "Hryvnia",
    code: "UAH",
    symbol: "₴",
    symbol_native: "₴" },
  AE: {
    country_name: "United Arab Emirates",
    currency: "Dirham",
    code: "AED",
    symbol: "AED",
    symbol_native: "د.إ.‏" },
  UY: {
    country_name: "Uruguay",
    currency: "Peso",
    code: "UYU",
    symbol: "$U",
    symbol_native: "$" },
  UZ: {
    country_name: "Uzbekistan",
    currency: "Som",
    code: "UZS",
    symbol: "UZS",
    symbol_native: "UZS" },
  VU: {
    country_name: "Vanuatu",
    currency: "Vatu",
    code: "VUV",
    symbol: "VUV",
    symbol_native: "VUV" },
  VE: {
    country_name: "Venezuela",
    currency: "Bolivar",
    code: "VEF",
    symbol: "Bs.F.",
    symbol_native: "Bs.F." },
  VN: {
    country_name: "Vietnam",
    currency: "Dong",
    code: "VND",
    symbol: "₫",
    symbol_native: "₫" },
  YE: {
    country_name: "Yemen",
    currency: "Rial",
    code: "YER",
    symbol: "YR",
    symbol_native: "ر.ي.‏" },
  ZM: {
    country_name: "Zambia",
    currency: "Kwacha",
    code: "ZMK",
    symbol: "ZK",
    symbol_native: "ZK" },
  ZW: {
    country_name: "Zimbabwe",
    currency: "Zimbabwe Dollar",
    code: "ZWD",
    symbol: "ZWD",
    symbol_native: "ZWD" },
  AX: {
    country_name: "Aland Islands",
    currency: "Euro",
    code: "EUR",
    symbol: "€",
    symbol_native: "€" },
  AO: {
    country_name: "Angola",
    currency: "Angolan kwanza",
    code: "AOA",
    symbol: "AOA",
    symbol_native: "AOA" },
  AQ: {
    country_name: "Antarctica",
    currency: "Antarctican dollar",
    code: "AQD",
    symbol: "AQD",
    symbol_native: "AQD" },
  BA: {
    country_name: "Bosnia and Herzegovina",
    currency: "Bosnia and Herzegovina convertible mark",
    code: "BAM",
    symbol: "KM",
    symbol_native: "KM" },
  GH: {
    country_name: "Ghana",
    currency: "Ghana cedi",
    code: "GHS",
    symbol: "GH₵",
    symbol_native: "GH₵" },
  GG: {
    country_name: "Guernsey",
    currency: "Guernsey pound",
    code: "GGP",
    symbol: "GGP",
    symbol_native: "GGP" },
  IM: {
    country_name: "Isle of Man",
    currency: "Manx pound",
    code: "GBP",
    symbol: "£",
    symbol_native: "£" },
  ME: {
    country_name: "Montenegro",
    currency: "Euro",
    code: "EUR",
    symbol: "€",
    symbol_native: "€" },
  PS: {
    country_name: "Palestinian Territory",
    currency: "Jordanian dinar",
    code: "JOD",
    symbol: "JD",
    symbol_native: "د.أ.‏" },
  BL: {
    country_name: "Saint Barthelemy",
    currency: "Euro",
    code: "EUR",
    symbol: "€",
    symbol_native: "€" },
  SH: {
    country_name: "Saint Helena",
    currency: "Saint Helena pound",
    code: "GBP",
    symbol: "£",
    symbol_native: "£" },
  MF: {
    country_name: "Saint Martin (French part)",
    currency: "Netherlands Antillean guilder",
    code: "ANG",
    symbol: "ANG",
    symbol_native: "ƒ" },
  PM: {
    country_name: "Saint Pierre and Miquelon",
    currency: "Euro",
    code: "EUR",
    symbol: "€",
    symbol_native: "€" },
  RS: {
    country_name: "Serbia",
    currency: "Serbian dinar",
    code: "RSD",
    symbol: "din.",
    symbol_native: "дин." },
  XX: {
    country_name: "Unknow",
    currency: "Euro",
    code: "EUR",
    symbol: "€",
    symbol_native: "€" },
  noDecimals:['BIF','CLP','DJF','GNF','JPY','KMF','KRW','MGA',
  'PYG','RWF','VND','VUV','XAF','XOF','XPF'], }
